version: 2.1
jobs:
    build:
        docker:
            - image: satantime/puppeteer-node:12.16-buster
        steps:
            - checkout
            - restore_cache:
                  key: dependency-cache-{{ checksum "package-lock.json" }}
            - run:
                  name: install-dependencies
                  command: npm install
            - save_cache:
                  key: dependency-cache-{{ checksum "package-lock.json" }}
                  paths:
                      - ./node_modules
            - run:
                  name: angular-test
                  command: npm run test -- --single-run --no-progress
            - store_test_results:
                  path: ./test-reports
            - store_artifacts:
                  path: ./test-reports/coverage
                  prefix: coverage
            - run:
                  name: angular-lint
                  command: npm run lint
